In [4]:
import numpy as np

a = np.array([1,2,3,4])
b = a
a = a+1 
print(b)
print(a)
b = b + 3
print(b)

[1 2 3 4]
[2 3 4 5]
[4 5 6 7]


In [6]:
import numpy as np                    # import necessary dependency with alias as np
from numpy.linalg import norm
arr=np.array([1,3,5])                   #formation of an array using numpy library
maxnorm =norm(arr,np.inf)                          # here inf represents the order of the norm
print(maxnorm)

5.0
